name: Test And Sonar

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm install      
    - run: npm run ci

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
